class DocumentError(Exception): ...

class DuplicateDocument(DocumentError):
    def __init__(self, document_id):
        self.document_id = document_id

class DocumentParseError(DocumentError): ...
class DocumentRetryableError(DocumentParseError): ...
class DocumentFatalError(DocumentParseError): ...